server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DS0708/config-repo  #?? ??? ?? ???? ??? ?? ? ???? URL
          default-label: main   #??? ? ??? ?? ????? main ????? ?? ???? ??
          timeout: 5    # config server? git? ?? ???? ?? ?? ??? ???? ??? ???? ??
          clone-on-start: true  #??? ???? ?? ???? ???? ??? ??
          force-pull: true    #???? ?? ???? ?????, ?? ???? ?? ???? ??? ? ???, ? ??? ?? config server? ?? ?? ???? ??? ???? ???? ??